version: '3.8'


x-default-healthcheck: &default-healthcheck
  interval: 10s
  timeout: 2s
  retries: 3


services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    ports:
      - "27017:27017"
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
#    volumes:
#      - zookeeper-data:/zookeeper_data
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "/opt/bitnami/zookeeper/bin/zkServer.sh", "status"]

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://127.0.0.1:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - "9092:9092"
#    volumes:
#      - kafka-data:/kafka_data
    depends_on:
      - zookeeper
    healthcheck:
      <<: *default-healthcheck
      test:
        [
          "CMD",
          "/opt/bitnami/kafka/bin/zookeeper-shell.sh",
          "zookeeper:2181",
          "get",
          "/brokers/ids/1",
        ]
  